version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    hostname: redis
    restart: unless-stopped

  db:
    image: postgres:9
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db-data
        target: /db-data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

  poll:
    image: poll
    build:
      context: ./poll
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    networks:
      - poll-tier
    restart: unless-stopped
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: ./Dockerfile
    networks:
      - back-tier
    restart: unless-stopped
    environment:
      - REDIS_HOSTNAME=redis
      - POSTGRES_HOSTNAME=db
    depends_on:
      - redis
      - db

  result:
    image: result
    build:
      context: ./result
      dockerfile: ./Dockerfile
    ports:
      - "5001:80"
    networks:
      - result-tier
    restart: unless-stopped
    environment:
    - POSTGRES_HOSTNAME=db
    depends_on:
      - db

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: